### ISSUE TITLE
QML Not working

### ISSUE THREAD

**Issue by nikialeksey** [pyqt/python-qt5#16]
Hello! I have a problem with qml: i can't start my app on python2.7.
This is my python code `main.py`: 
```
from PyQt5.QtCore import QUrl, QObject, pyqtSlot
from PyQt5.QtGui import QGuiApplication
from PyQt5.QtQuick import QQuickView

if __name__ == '__main__':
    import sys

    app = QGuiApplication(sys.argv)

    view = QQuickView()
    view.setResizeMode(QQuickView.SizeRootObjectToView)
    view.setSource(
        QUrl.fromLocalFile('main.qml')
    )
    view.show()

    sys.exit(app.exec_())
```
and qml code `main.qml`:
```
import QtQuick 2.0

Rectangle {
    width: 500
    height: 400
}
```

**Comment by mottosso** [comment]
Hi @nikialeksey, thanks for sharing.

However, your example works well for me. Could you post the exact error message, and a step-by-step on how you installed python-qt5?

**Comment by nikialeksey** [comment]
Ok! I install python2 as Anaconda on my Windows 8.1 64 bit (https://store.continuum.io/cshop/anaconda/), then I call `C:\Anaconda\Scripts\pip.exe install python-qt5` and it worked fine. After install I tried to run my program (python + qml) but my PyCharm told me 

```
C:\Anaconda\python.exe E:/qt-workspace/testPyQT5/main.py
Process finished with exit code -1073741819 (0xC0000005)
```

Sorry for my bad english.

**Comment by mottosso** [comment]
Hm, I'm not familiar with either Anaconda or PyCharm.

What happens when you try running it from the command-line?

```bash
$ python main.py
```

**Comment by nikialeksey** [comment]
I remove my Anaconda and install python 2.7 from official site for am64 acrh and run `python main.py` from command line. Windows show me "programm python.exe doesn't work". It's magic)

**Comment by mottosso** [comment]
Hey @nikialeksey, have you found a solution yet? I'm still not noticing these problems over here :(

**Comment by nikialeksey** [comment]
Hi) not yet. Finally I took `PyQt5` with `SIP` and it works fine for me, but i got a problem with deploy. So I want to try `python-qt5` install on python with other architecture. I will let you know if I solved this problem!

**Comment by mottosso** [comment]
Ok, good luck!

**Comment by mottosso** [comment]
Assuming this worked out for you, let me know otherwise.
