### ISSUE TITLE
ImportError: DLL load failed: %1 not a valid win32 application!

### ISSUE THREAD

**Issue by chinant** [pyqt/python-qt5#17]
I run the below code in win8.1 64bit and python 2.7.3:

    import sys
    from PyQt5 import QtWidgets

results in:

     ImportError: DLL load failed: %1 not a valid win32 application!

**Comment by mottosso** [comment]
Hi @chinant,

Could you try this?

```bat
:: From a cmd.exe terminal
$ pip install python-qt5
$ python
```

```python
>>> # Continuing from Python
>>> import platform
>>> platform.architecture()  # Make sure your Python is 64-bit
('64bit', 'WindowsPE')
>>> from PyQt5 import QtWidgets
>>> # Did it throw an error?
```

**Comment by chinant** [comment]
Thank you @mottosso .
It need python 64bit, this issue was solve.

**Comment by mottosso** [comment]
Perfect!
