### ISSUE TITLE
Cannot install from git via pip

### ISSUE THREAD

**Issue by jacksonofalltrades** [pyqt/python-qt5#18]
To start, I should mention, I believe I specifically need to install from git rather than pip since I had problems getting pyinstaller working with PyQt5 otherwise.

I'd like to be able to improve my build process by having the install go through a requirements.txt file.

However, it seems I am unable to put this in my requirements.txt:
git+git://github.com/pyqt/python-qt5.git

That is, on Windows, I get this error:
"No files/directories in <windows pip temp path>"

The internet says this is because it's not a python package?

Any suggestions?
Thanks!

**Comment by mottosso** [comment]
> However, it seems I am unable to put this in my requirements.txt:

That's an interesting use-case, have not tried this with requirements.txt before. Are you sure you it supports Git repositories to begin with? Some quick googling reveals that you might have to adopt a dedicated syntax.

- https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

Other than that, as whether it is installable via pip or not, does this work for you?

```bash
$ pip install git+git://github.com/pyqt/python-qt5.git
```

**Comment by jacksonofalltrades** [comment]
Btw, this is on Windows 8 (32-bit) (a VM, I don't install Windows for real as a rule if I can help it...)
Yes, the last line above is what I used. I will include the full console output here:
<code>
PS C:\Users\IEUser> C:\tools\python2\Scripts\pip install git+git://github.com/py
qt/python-qt5
c:\tools\python2\lib\site-packages\pip\pep425tags.py:89: RuntimeWarning: Config
variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
c:\tools\python2\lib\site-packages\pip\pep425tags.py:93: RuntimeWarning: Config
variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
  warn=(impl == 'cp')):
c:\tools\python2\lib\site-packages\pip\pep425tags.py:99: RuntimeWarning: Config
variable 'Py_UNICODE_SIZE' is unset, Python ABI tag may be incorrect
  sys.version_info < (3, 3))) \
Collecting git+git://github.com/pyqt/python-qt5
  Cloning git://github.com/pyqt/python-qt5 to c:\users\ieuser\appdata\local\temp
\pip-usqm00-build
No files/directories in c:\users\ieuser\appdata\local\temp\pip-usqm00-build\pip-
egg-info (from PKG-INFO)
</code>

**Comment by jacksonofalltrades** [comment]
Oh, hm, looking at this, I did seem to leave off the .git. Let me try once more with that.

**Comment by jacksonofalltrades** [comment]
(I'm not sure what the deal is with those runtime warnings...)

**Comment by jacksonofalltrades** [comment]
Ok, even adding the .git, same exact issue.

**Comment by jacksonofalltrades** [comment]
That's interesting. I read the stackoverflow post you link to above, and tried adding "-e" and get this:
<code>--editable=git+https://github.com/pyqt/python-qt5.git is not the right format; i
t must have #egg=Package</code>

So is it possible you just need to add this egg thing?

**Comment by mottosso** [comment]
Are you running this from cmd.exe? That looks like Powershell, I haven't tried, but are you sure pip is compatible with Powershell?

**Comment by jacksonofalltrades** [comment]
It is Powershell, and I have pip working fine for other packages.

**Comment by mottosso** [comment]
Ah, how about the Git extension? Maybe it's a limitation there.

**Comment by jacksonofalltrades** [comment]
Not sure...I can try on OSX and see if the same problem occurs.

**Comment by mottosso** [comment]
If this is still an issue, feel free to reopen this.

**Comment by arpit-goel** [comment]
Hi @mottosso 
I've been encountering same issue on Ubuntu 14.04. I'm trying to install it in a virtualenv, no matter what I try, it gives `No files/directories in /path_to_build/python-qt5/pip-egg-info (from PKG-INFO)`. Here's the list of commands I tried:

1. `pip install python-qt5`
2. `pip install git+git://github.com/pyqt/python-qt5.git`
3. `pip install git+git://github.com/pyqt/python-qt5.git@e58d0b106af8d7e419827034827d074338bbaa3e`

I also tried with the -e like mentioned above in thread, received same error:
`--editable=git+git://github.com/pyqt/python-qt5.git@e58d0b106af8d7e419827034827d074338bbaa3e is not the right format; it must have #egg=Package`.

There seems to be some issue with the package, can you please look into this?

**Comment by mottosso** [comment]
This project is only built for Windows. You'll have to build it yourself for Ubuntu and others.

**Comment by ruidc** [comment]
This package is for Windows only, for Ubuntu 14.04 I suggest you see http://askubuntu.com/questions/662595/best-way-to-install-pyqt5-for-python-2-7-on-ubuntu-14-04

**Comment by oca159** [comment]
I have the same problem in macOS Sierra. I am receiving the error 
**No files/directories in /private/var/folders/9b/df5qj2h11cd_fg65c5t2w6g00000gn/T/pip-build-yaKQka/python-qt5/pip-egg-info (from PKG-INFO)**

**Comment by The-Compiler** [comment]
@oca159 from two comments above yours:

> This project is only built for Windows. You'll have to build it yourself for Ubuntu and others.

:wink:

Nowadays you can install `PyQt5` via `pip`, though I'm not sure whether that's true or not. I personally use Homebrew there.

**Comment by mottosso** [comment]
Yes, recommended is Homebrew on MacOS and your native package manager for Ubuntu and other Linux flavours.

If you would rather build, there are instructions for Windows and Ubuntu in the Wiki for this project, that may also apply to MacOS.

- [Ubuntu](https://github.com/pyqt/python-qt5/wiki/Compiling-PyQt5-on-Ubuntu-12.04)
- [Windows](https://github.com/pyqt/python-qt5/wiki/Building-Qt-with-Visual-Studio-2015)

Additionally, since about 4-6 months ago, PyQt5 is available via pip for Python 3.5.

```bash
$ pip3 install pyqt5
```

**Comment by anthrotype** [comment]
Why isn't the pip method the recommended one? It works flawlessly on all three platforms, even inside a virtual environment, with the same `pip install PyQt5` command.

**Comment by mottosso** [comment]
Hi @anthrotype,

This project is exclusively for for users running Python 2.7 on Windows.

PyQt5 exists on pip only for Python 3.5, see [here](https://pypi.python.org/pypi/PyQt5/5.7), under "Py Version".

**Comment by anthrotype** [comment]
Oops, sorry I had forgotten that.
Cheers

**Comment by RK1975** [comment]
Not working on Windows 10.  I tried:
`pip install git+git://github.com/pyqt/python-qt5.git`
and just get Files/directories not found in c:\users\...

**Comment by mottosso** [comment]
This seems like a problem with either `pip` or `git`.

Try this.

```python
$ mkdir c:\pythonpath
$ pip install git+git://github.com/pyqt/python-qt5.git --target c:\pythonpath
```

It should install it into that directory, and then you can move it manually.
