### ISSUE TITLE
Saving and restoring a PyQt Application state ?

### ISSUE THREAD

**Issue by rishabh135** [pyqt/python-qt5#22]
I have developed a PyQt4 application , and it has a stacked widget structure where each widget in the stacked-widget is described by a separate class , when I started trying out to save the state of the application , I was unable to find any , there was a QDataStream which sounded promising but I would have to manually save each PyQt element's state and settings , is there a better and more elegant way ? Thanks .

**Comment by mottosso** [comment]
This would be an excellent topic for the PyQt mailing list.
