### ISSUE TITLE
tutorials and samples

### ISSUE THREAD

**Issue by catafest** [pyqt/python-qt5#23]
Can pyqt5 has tutorials and samples and where ?

**Comment by mottosso** [comment]
They were taken out to reduce the size of the project, but can be found in git history.

- https://github.com/pyqt/python-qt5/tree/d9e46032b358635b2f9308d775bfb51f8dd4a147/src/PyQt-gpl-5.3.2/examples

**Comment by catafest** [comment]
I need some effects make with gui and pyqt5 and docs to read about this issue.
