### ISSUE TITLE
Installing Bug? (designer and pyuic.bat)

### ISSUE THREAD

**Issue by Ch3fk0ch88** [pyqt/python-qt5#24]
Hi,
i try to install PyQt5 but it will not work.

I testes
`pip3 install pyqt5` but than there is no designer.exe (and no pyuic5.bat)

`pip install python-qt5` there is a a designer.exe (but no pyuic5.bat)
When i start the designer.exe i get a error:

> This application failed to start because it could not find or load the Qt platform plugin "windows".
> Reinstalling the applictaion may fiy this problem.

I think this is cause its for installation on Python 2.7?

I run Python 3.6

So, which is the right way to install PyQt5 on Python 3.6 with designer and uic.bat?

I hope u can help

**Comment by mottosso** [comment]
Hi @Ch3fk0ch88, this version will only work with the 64-bit version of Python 2.7.

If you're having trouble with that, try one of the other installation methods listed in the [README](https://github.com/pyqt/python-qt5).

As for Python 3.6, perhaps ask in with the [PyQt5 mailing list](https://www.riverbankcomputing.com/mailman/listinfo/pyqt).
