### ISSUE TITLE
Could not find QtWebEngineProcess.exe

### ISSUE THREAD

**Issue by ljx0517** [pyqt/python-qt5#25]
i follow the wiki build qt5.7.1 on   vs2015
everything is fine
but QWebEngineView
simple code
 
```
import sys

from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl
def main():
    app = QApplication(sys.argv)
    window = QMainWindow()
    window.setWindowTitle('PyQt Demo')
    window.setGeometry(320, 180, 960, 540)
    view = QWebEngineView()
    view.load(QUrl('http://leafletjs.com/')) # error here
    window.setCentralWidget(view)
    window.show()
    sys.exit(app.exec_())
if __name__ == '__main__':
    main()
```

and display 
`Could not find QtWebEngineProcess.exe`
how to solve this
thanks

**Comment by mottosso** [comment]
Sorry, can't help you with that. Try the https://riverbankcomputing.com/mailman/listinfo/pyqt

**Comment by ljx0517** [comment]
thanks all the same,
i do some research and found just copy QtWebEngineProcess.exe from PyQt5 folder to python root folder,
and then the script can run
