### ISSUE TITLE
cannot find pyuic5.bat

### ISSUE THREAD

**Issue by dkvv** [pyqt/python-qt5#29]
Hi there,I've been using python27 for several days to do a homework,Im new to it and then my teacher asked me to add a GUI for my program,by PyQt,I looked up on the riverbank website and learned that binary wheel was only for python35 and above, build and install SIP and PYQT5 was too complex for me and I found this,using pip install python-qt5, I successfully installed pyqt5,but when I did as the reference "pycuic5 xx.ui ",it didnt work,and I didnt find the pyuic5 in the python27/scripts folder either.

how can I fix it?
and is there anything else that's different from the "offical installation"?

thanks very much!

**Comment by mottosso** [comment]
Hi @dkvv, sorry for the late reply.

In place of this file, try running this.

```bash
python -m PyQt5.uic.pyuic
```

Or make your own, with this.

**pyuic5.bat**

```bash
python -m PyQt5.uic.pyuic %*
```

**Comment by dkvv** [comment]
@mottosso thx for the reply!! and thank you for this repo,a great convienience for me!
