### ISSUE TITLE
"class ProxyBase(metaclass=ProxyMetaclass)" invalid syntax

### ISSUE THREAD

**Issue by CastielHou** [pyqt/python-qt5#33]
I have Python 2.7.14 installed. 
When I installed python-qt5 and executed `python setup.py install`, I got this error:

> byte-compiling build\bdist.win-amd64\egg\PyQt5\uic\port_v3\proxy_base.py to proxy_base.pyc
  File "build\bdist.win-amd64\egg\PyQt5\uic\port_v3\proxy_base.py", line 26
    class ProxyBase(metaclass=ProxyMetaclass):
> SyntaxError:  invalid syntax

But the test on Wiki can still be passed. I had also checked `proxy_base.py` mentioned above, but couldn't find a way to solve it.

So how can I fix this error? Thanks in advance!

**Comment by mottosso** [comment]
You can delete that folder, it doesn't need to exist as it's for Python 3 only.
