### ISSUE TITLE
No files/directories in /private/var/folders/57/w7_202cd2nldvlyzdywk6zt0mzhx88/T/pip-build-noijkH/python-qt5/pip-egg-info (from PKG-INFO)

### ISSUE THREAD

**Issue by zui-coding** [pyqt/python-qt5#36]
Ok,I install python-qt5 with pip:
```python
 pip install python-qt5
```
throw exception:
```shell
Collecting python-qt5
  Using cached python-qt5-0.1.10.zip
No files/directories in /private/var/folders/57/w7_202cd2nldvlyzdywk6zt0mzhx88/T/pip-build-noijkH/python-qt5/pip-egg-info (from PKG-INFO)
```
what's mean? How can i do? Please help me!! Thanks

**Comment by tokejepsen** [comment]
Did you use Conda to install with ```pip```?

**Comment by zui-coding** [comment]
@tokejepsen ,No,`pip` when installing python,python more than 2.7 of the version with PIP

**Comment by tokejepsen** [comment]
It might be that your cache files did not download correctly.

Try install without using the cache, https://stackoverflow.com/questions/9510474/removing-pips-cache:

```
pip --no-cache-dir install python-qt5
```

**Comment by zui-coding** [comment]
@tokejepsen ：
```shell
pip --no-cache-dir install python-qt5
Collecting python-qt5
  Downloading python-qt5-0.1.10.zip (57.5MB)
    100% |████████████████████████████████| 57.5MB 21.8MB/s
No files/directories in /private/var/folders/57/w7_202cd2nldvlyzdywk6zt0mzhx88/T/pip-build-pakQuJ/python-qt5/pip-egg-info (from PKG-INFO)
```
I think python-qt5 should be downloaded. Is there any problem in the computer environment？

**Comment by mottosso** [comment]
That's not Windows. This release is Window-only.

https://github.com/pyqt/python-qt5#unofficial-pyqt5-via-pypi-for-python-27-64-bit-on-windows
