### ISSUE TITLE
ModuleNotFoundError: No module named 'util'

### ISSUE THREAD

**Issue by siemlohuis** [pyqt/python-qt5#38]
When I try to install python-qt5 and I do:

`python -c "import util;util.createqtconf()"`

In the windows cmd I get the error:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'util'`

How can I solve this?
Thanks for reading!

**Comment by mottosso** [comment]
Make sure you're in the python-qt5 directory when running it.

```bash
$ git clone https://github.com/pyqt/python-qt5.git
$ cd python-qt5
$ python -c "import util;util.createqtconf()"
```

As the `util.py` file is in that directory, [here](https://github.com/pyqt/python-qt5/blob/master/util.py).
