### ISSUE TITLE
Explain how to build the DLLs from source

### ISSUE THREAD

**Issue by madprog** [pyqt/python-qt5#40]
Thank you for providing these DLLs.

Would it be possible to provide additional information on how to re-create them from the Qt5 community source code?

More precisely, I faced this problem when trying to compile them myself: Python2.7 is requiring a build with Visual C++ 9.0 (as stated in [the WindowsCompilers Python wiki page](https://wiki.python.org/moin/WindowsCompilers#Which_Microsoft_Visual_C.2B-.2B-_compiler_to_use_with_a_specific_Python_version_.3F)), and Qt5 uses the C++ 2010 syntax which is not supported by Visual C++ 9.0.

What magic did you use to bypass this contradiction? Would it be a good idea to add this information in the README?

**Comment by mottosso** [comment]
Certainly @madprog, there are instructions in the [Wiki](https://github.com/pyqt/python-qt5/wiki), primarily [this](https://github.com/pyqt/python-qt5/wiki/Updating-the-repository), but be warned they are both lengthy and relatively old (for 5.4). 

Yes it would be a good idea to have it in the README, if you run through it it would be great to hear back with your experiences such that we could potentially update that and give it more exposure.

> What magic did you use to bypass this contradiction? Would it be a good idea to add this information in the README?

The magic is simply to ignore that Python is built with an older VS, and use it anyway. I've heard rumours about there being issues with that, but having used it for a number of years now I've learnt to ignore them. Although nowadays I use Python 3 almost exclusively, for which this repo is no longer necessary as it's available via `pip install PyQt5`

**Comment by madprog** [comment]
Thank you @mottosso for your answer. I will use your repository for now, and try to build it from scratch later using the Wiki instructions (of course I should have looked in the Wiki first!)
