### ISSUE TITLE
QtWebEngineWidgets not found after update from 5.10.1

### ISSUE THREAD

**Issue by further-reading** [pyqt/python-qt5#43]
I just updated my pyqt5 version to 5.11.3 and started getting a module not found error when trying to import QTWebEngine Widgets using `from PyQt5.QtWebEngineWidgets import *`. Upon reversion to 5.10.1 is started working again. This is on Python 3.6 running on Windows 10.

Was there a change to QtWebEngineWidgets between those versions and if so what should I use to import and use web engine functions now? There's been so many changes to the QTWebEngine that it's hard to track what is relevant to more recent versions.

**Comment by Schizo** [comment]
I've realized the same issue, at the time of my writing, if you do 

`pip install python-qt5` you get version **python-qt5-0.1.10** which do have QtWebKitWidgets

However, using the git approach mentioned in the docs

`pip install git+git://github.com/pyqt/python-qt5.git` will leave you with **python-qt5-0.3.0**

**Comment by The-Compiler** [comment]
If you're using the official PyQt5 distribution (which you probably should, as it's much more recent than what you get via this unofficial repo), QtWebEngine got split into a separate `PyQtWebEngine` package.

**Comment by Schizo** [comment]
Well, if you are using `Python 2.7` there is no other option than using this repository.

**Comment by The-Compiler** [comment]
There is (building PyQt from sources) - however, if you're using Python 2.7, you probably should switch to Python 3 some time soon :wink:

**Comment by Schizo** [comment]
Building from source is an adventure, we are going to switch to 3 soon but due to legacy reasons, we need to maintain python 2.7.

**Comment by further-reading** [comment]
Thanks @The-Compiler for expalining! Since this looks to be WAI I'll close the issue.
