### ISSUE TITLE
using pyqt-tools

### ISSUE THREAD

**Issue by mehrshaad** [pyqt/python-qt5#56]
hey, guys, I got an issue:
I've been working on a .py file that used to convert it from .ui.
but now after editing and adding new functions to the .py file I've wanted to edit my .ui file in qt designer but if I use the new .py file (that converted from the new .ui file) my entered functions will be erased.
if you can please help or show me a way to save my functions and use the new .ui I designed.

**Comment by The-Compiler** [comment]
If you look at the top of those files, they say something like:

```python
# WARNING! All changes made in this file will be lost!
```

Instead of editing that file, see https://www.riverbankcomputing.com/static/Docs/PyQt5/designer.html

**Comment by mehrshaad** [comment]
> If you look at the top of those files, they say something like:
> 
> ```python
> # WARNING! All changes made in this file will be lost!
> ```
> 
> Instead of editing that file, see https://www.riverbankcomputing.com/static/Docs/PyQt5/designer.html

thanks!
