### ISSUE TITLE
pip3 support

### ISSUE THREAD

**Issue by fabiencastan** [pyqt/python-qt5#8]

**Comment by mottosso** [comment]
Do you mean PyQt5 for Python 3?

**Comment by fabiencastan** [comment]
yes

**Comment by mottosso** [comment]
I was planning on aligning with [how some Linux distributions ship PyQt5][linux], i.e. `python3-qt5` and to store that distribution here: https://github.com/pyqt/python3-qt5

Let's keep issues regarding this version in there.

[linux]: http://rpmfind.net/linux/rpm2html/search.php?query=python3-qt5
